pipeline:
  identifier: Build_skanodia1_docker_helloworld_node_microservice_1740699303910
  name: Build docker-helloworld-node-microservice
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1740698630998
        repoName: skanodia1/docker-helloworld-node-microservice
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: account.GCP_Test_Connector
                    host: https://us-west2-docker.pkg.dev/
                    projectID: focal-plateau-451819-i9/harness-excercise-ar
                    imageName: test
                    tags:
                      - test1tag
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
